# Generated by Django 6.0 on 2026-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['price_per_gallon'], name='route_api_f_price_p_c570ad_idx'),
        ),
    ]
